### ISSUE TITLE
Problem with output format

### ISSUE THREAD

**Issue by overthink** [abhinavabcd/sortable_code_matchings#1]
Hi there.

There is a problem with your output that is preventing me from evaluating your solution.  The value of the "listings" field should be an array of listing objects, but right now yours is an array of strings:

e.g.
yours:
```json
{"listings": ["{\"title\":\"Olympus D-360L 1.2MP Digital Camera\",\"manufacturer\":\"Olympus\",\"currency\":\"USD\",\"price\":\"79.95\"}\n"], "product_name": "Olympus_D-360L"}
```
expected:
```json
{"listings": [{"title":"Olympus D-360L 1.2MP Digital Camera", "manufacturer": "Olympus", "currency": "USD", "price":"79.95"}], "product_name": "Olympus_D-360L"}
```

If you could please fix this up I can take another look.  Many thanks!

Mark Feeney (from sortable.com)

**Comment by abhinavabcd** [comment]
@overthink , I have made the change , so sorry for the mistake. 
Thanks.

**Comment by overthink** [comment]
Thanks for the very fast fix!
